services:
  application:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USR=${DB_USR}
      - DB_PWD=${DB_PWD}
    networks:
      - service_net
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service
    ports:
      - "5432:5432"
    networks:
      - service_net
    volumes:
      - pg_data:/var/lib/postgresql/data

networks:
  service_net:
    driver: bridge

volumes:
  pg_data:
